### ISSUE TITLE
The new v0.0.5 doesn't work with Apollo Client

### ISSUE THREAD

**Issue by abdonrd** [LarsDenBakker/es-dev-server-rollup#4]
The error is:

<img width="1410" alt="Screenshot 2020-08-01 at 17 54 42" src="https://user-images.githubusercontent.com/1007051/89105294-33200580-d420-11ea-8e8c-2d6e247f0917.png">

**Comment by abdonrd** [comment]
If I back to the v0.0.4 all works.

**Comment by LarsDenBakker** [comment]
I'm trying to reproduce this, which package should I install/import to try it out?

**Comment by abdonrd** [comment]
Example here:

https://github.com/IBM/pwa-lit-template/compare/apolloclient...apolloclient-es-dev-server-rollup

```
const { wrapRollupPlugin } = require('es-dev-server-rollup');
const commonjs = require('@rollup/plugin-commonjs');

module.exports = {
  plugins: [
    wrapRollupPlugin(
      commonjs({
        include: [
          '**/fast-json-stable-stringify/**/*',
          '**/graphql-tag/**/*',
          '**/zen-observable/**/*'
        ]
      })
    )
  ]
};
```

**Comment by LarsDenBakker** [comment]
Thanks for reporting - can you try with 0.0.6?

**Comment by abdonrd** [comment]
Yay! It works, thanks @LarsDenBakker!
